configs:
  #  [logger configs]
  log_level: "info" # available values: [debug, info, warn, error]
  log_into_file: false
  log_file_path: ""
  log_file_max_size: 100
  log_file_backups: 15
  log_file_max_age: 1 # in days

  # [ipfs config]
  jwt_token: "your_jwt_token"

  # [ton wallet]
  mnemonic_phrase: "your_mnemonic_phrase"