configs:
  #  [logger configs]
  log_level: "info" # available values: [debug, info, warn, error]
  log_into_file: false
  log_file_path: ""
  log_file_max_size: 100
  log_file_backups: 15
  log_file_max_age: 1 # in days

  # [ipfs config]
  pinata_jwt_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIwYjAwZTVhMC0yYTE1LTQyOWEtYWZmMi04Nzg0MDdjMzBiMDciLCJlbWFpbCI6Imt1YW5keWtvZmZpY2FsQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiJjYmFjMGUwZGY4MTJlNzA3N2ExZiIsInNjb3BlZEtleVNlY3JldCI6ImQ2NjAxOGZhYmFmMzVhYzBkZDM4ZWM2NWU3YjZjNzhhOGIzYjYzZDE2YmJhNjUyNmZiZGRkMWJhZjY4Y2Y0YTgiLCJleHAiOjE3NzgzMzg0MjR9.5w8Xms7u2Aflm_CAYLk5TquvpzhKB116hMmBOkzBXMU"

  # [ton wallet]
  mnemonic_phrase: "saddle cricket rent frequent tortoise increase clog judge skin blouse whale coral school increase draw tower task afford toward cactus city silent type machine"